#!/bin/bash
# build_portmaster.sh
# Creates the exact structure for Miyoo Flip v2 (Spruce OS) PortMaster

set -e

GAME_NAME="PIXELRAIDERS"
BUILD_DIR="dist"

echo "=== Building PortMaster Package for $GAME_NAME ==="

# 1. Clean and create build structure
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/$GAME_NAME"

# 2. Detect deployer's local IP address
echo "Detecting deployer's local IP address..."
DEPLOYER_IP=""

# Try different methods to get local IP (works on macOS and Linux)
# macOS: try ipconfig getifaddr
if [ -z "$DEPLOYER_IP" ] && command -v ipconfig &>/dev/null; then
    # Try common macOS interface names
    for iface in en0 en1 en2 eth0; do
        DEPLOYER_IP=$(ipconfig getifaddr "$iface" 2>/dev/null || echo "")
        if [ -n "$DEPLOYER_IP" ]; then
            break
        fi
    done
fi

# Linux: try hostname -I
if [ -z "$DEPLOYER_IP" ] && command -v hostname &>/dev/null; then
    DEPLOYER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")
fi

# Fallback: try ifconfig (works on both macOS and Linux)
if [ -z "$DEPLOYER_IP" ] && command -v ifconfig &>/dev/null; then
    # Try to get IP from ifconfig (works on macOS and most Linux)
    DEPLOYER_IP=$(ifconfig 2>/dev/null | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -n1 || echo "")
fi

# macOS fallback: try route command
if [ -z "$DEPLOYER_IP" ] && command -v route &>/dev/null && [ "$(uname)" = "Darwin" ]; then
    INTERFACE=$(route get default 2>/dev/null | grep interface | awk '{print $2}' || echo "")
    if [ -n "$INTERFACE" ]; then
        DEPLOYER_IP=$(ifconfig "$INTERFACE" 2>/dev/null | grep "inet " | awk '{print $2}' | head -n1 || echo "")
    fi
fi

if [ -z "$DEPLOYER_IP" ]; then
    echo "⚠️  Warning: Could not detect local IP address. Using localhost instead."
    echo "   You may need to manually set the API URL in the .env file."
    DEPLOYER_IP="localhost"
else
    echo "✓ Detected deployer IP: $DEPLOYER_IP"
fi

# 3. Create .env file with deployer's IP for API
echo "Creating .env file with deployer IP..."
cat > .env << EOF
# Auto-generated by build_portmaster.sh
# API configuration for multiplayer - uses deployer's IP address
API_BASE_URL=http://${DEPLOYER_IP}:3000
RELAY_HOST=${DEPLOYER_IP}
RELAY_PORT=12346
EOF

echo "✓ Created .env file:"
echo "  API_BASE_URL=http://${DEPLOYER_IP}:3000"
echo "  RELAY_HOST=${DEPLOYER_IP}"
echo "  RELAY_PORT=12346"
echo ""

# 4. Package the .love file
echo "Creating $GAME_NAME.love..."
# Zip everything in current dir into the .love file
# Excluding build files and hidden git/system files
# Note: .env is NOT excluded so it will be included in the package
zip -9 -r "$BUILD_DIR/$GAME_NAME/$GAME_NAME.love" . \
     -x "*.git*" -x "dist/*" -x "server/*" -x "tools/*" -x "build_portmaster.sh" -x "*.DS_Store" -x "raw_udp_test.lua" -x "debug/*"

# 5. Create the Launcher (.sh)
echo "Creating $GAME_NAME.sh..."
cat > "$BUILD_DIR/$GAME_NAME.sh" << EOF
#!/bin/bash
# PortMaster Launcher for Pixel Raiders

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt

get_controls
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"

# Dynamic path resolution. We remove any trailing slashes to avoid // issues.
CLEAN_DIR=\$(echo "/\$directory" | sed 's:/*\$::')
GAMEDIR="\$CLEAN_DIR/$GAME_NAME"

# If not found in root, check in /ports/ subfolder
if [ ! -d "\$GAMEDIR" ]; then
    GAMEDIR="\$CLEAN_DIR/ports/$GAME_NAME"
fi

cd "$GAMEDIR"

# Setup saves path
export XDG_DATA_HOME="$GAMEDIR/saves"
export XDG_CONFIG_HOME="$GAMEDIR/saves"
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_CONFIG_HOME"

# Redirect all output to log.txt for debugging
exec > >(tee "\$GAMEDIR/log.txt") 2>&1
echo "--- Starting Pixel Raiders ---"
echo "Date: $(date)"
echo "GAMEDIR: $GAMEDIR"
echo "Device: $DEVICE_NAME ($DEVICE_ARCH)"

# Search for LÖVE binary
LOVE_BIN=""
# 1. Check PortMaster runtimes first (highest quality)
for ver in "11.5" "11.4"; do
    R_PATH="$controlfolder/runtimes/love_$ver/love.$DEVICE_ARCH"
    if [ -f "$R_PATH" ]; then
        LOVE_BIN="$R_PATH"
        export LD_LIBRARY_PATH="$(dirname "$R_PATH")/libs.$DEVICE_ARCH:$LD_LIBRARY_PATH"
        break
    fi
done

# 2. Check system paths fallback
if [ -z "$LOVE_BIN" ]; then
    for path in "/usr/bin/love" "/usr/local/bin/love" "/opt/love/bin/love"; do
        if [ -f "$path" ]; then
            LOVE_BIN="$path"
            break
        fi
    done
fi

if [ -z "$LOVE_BIN" ]; then
    echo "ERROR: LÖVE binary not found in runtimes or system paths!"
    exit 1
fi

echo "Using LÖVE binary: $LOVE_BIN"

# We use the basename of LOVE_BIN for gptokeyb to watch
LOVE_NAME=$(basename "$LOVE_BIN")

\$GPTOKEYB "\$LOVE_NAME" -c "\$GAMEDIR/$GAME_NAME.gptk" &
pm_platform_helper "\$LOVE_BIN"
"\$LOVE_BIN" "\$GAMEDIR/$GAME_NAME.love"

# Cleanup after exit
killall gptokeyb
pm_finish
EOF

chmod +x "$BUILD_DIR/$GAME_NAME.sh"

# 6. Create the Controller Mapping (.gptk)
echo "Creating $GAME_NAME.gptk..."
cat > "$BUILD_DIR/$GAME_NAME/$GAME_NAME.gptk" << 'EOF'
back = esc
start = enter

up = w
down = s
left = a
right = d

left_analog_up = w
left_analog_down = s
left_analog_left = a
left_analog_right = d

a = enter
b = esc
x = m
y = tab

l1 = tab
r1 = m
EOF

# 7. Create PortMaster metadata (port.json)
echo "Creating port.json..."
cat > "$BUILD_DIR/$GAME_NAME/port.json" << EOF
{
    "version": 1,
    "name": "$GAME_NAME",
    "items": ["$GAME_NAME.sh"],
    "items_opt": [],
    "attr": {
        "title": "Pixel Raiders",
        "desc": "Multiplayer walking simulator boilerplate.",
        "inst": "D-Pad to move. X/Y for Menu. Host on one device, Find on another!",
        "genres": ["multiplayer", "sim"],
        "porter": "Antigravity",
        "runtime": "love-11.4"
    }
}
EOF

echo ""
echo "=== DONE ==="
echo "Your PortMaster files are in the '$BUILD_DIR' folder:"
echo "1. $BUILD_DIR/$GAME_NAME.sh        <-- Move to /roms/ports/"
echo "2. $BUILD_DIR/$GAME_NAME/          <-- Move this whole FOLDER to /roms/ports/"
echo ""
echo "Installation on SD Card should look like this:"
echo "/roms/ports/$GAME_NAME.sh"
echo "/roms/ports/$GAME_NAME/$GAME_NAME.love"
echo "/roms/ports/$GAME_NAME/$GAME_NAME.gptk"
echo "/roms/ports/$GAME_NAME/port.json"
echo ""
echo "⚠️  IMPORTANT: Make sure your dev server is running on:"
echo "   - HTTP API: http://${DEPLOYER_IP}:3000"
echo "   - TCP Relay: ${DEPLOYER_IP}:12346"
echo "   And that your device can reach this IP on your local network!"
